name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: 读取仓库的内容
      uses: action/checkout@v4
      
    - name: 登陆Docker Hub
      uses: docker/login-action@v3
      with:
        username: ???
        password: ???
    
    - name: 构建并推送到Docker Hub
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: cap153/bili-sync-yt-dlp:latest
